/* ============================================================
   QUADRO A QUADRO — data.js
   Aqui vive a lista de séries e capítulos. É o único ficheiro que
   precisas de editar sempre que quiseres adicionar uma nova série
   ou novos capítulos a uma série existente.

   Este ficheiro NÃO guarda progresso de leitura (isso fica no
   localStorage de cada pessoa, no browser dela). Só descreve o
   "catálogo": que séries existem e que capítulos tem cada uma.

   ---------------------------------------------------------------
   FORMATO DE CADA SÉRIE:

   {
     id: "identificador-unico",   // string única, sem espaços/acentos
     title: "Nome da série",      // como aparece no ecrã
     color: "#D7263D",            // opcional — cor do "selo" da série (hex)
     chapters: [
       {
         id: 1,                       // único DENTRO da série
         title: "Nome/número do capítulo",   // ex: "Amazing Spider-Man #1"
         where: "Amazing Spider-Man Omnibus Vol. 1",  // opcional — onde ler
                                                        // (omite ou deixa "" se ainda
                                                        // não tiver volume/omnibus definido)
         optional: false               // opcional — true se for uma leitura
                                        // dispensável/tie-in (não afeta a
                                        // história principal da série)
       },
       { id: 2, title: "Amazing Spider-Man #2", where: "" },
       { id: 3, title: "Amazing Spider-Man Annual #1", where: "", optional: true },
       ...
     ]
   }

   EXEMPLO (descomenta e adapta para começares a testar):

   const SERIES = [
     {
       id: "asm-lee-ditko",
       title: "The Amazing Spider-Man (Lee/Ditko)",
       color: "#D7263D",
       chapters: [
         { id: 1, title: "Amazing Spider-Man #1", where: "Amazing Spider-Man Omnibus Vol. 1" },
         { id: 2, title: "Amazing Spider-Man #2", where: "Amazing Spider-Man Omnibus Vol. 1" },
         { id: 3, title: "Amazing Spider-Man #3", where: "" },
         { id: 4, title: "Amazing Spider-Man Annual #1", where: "", optional: true },
       ],
     },
     {
       id: "saga",
       title: "Saga",
       color: "#128C7E",
       chapters: [
         { id: 1, title: "Saga #1", where: "Saga Deluxe Vol. 1" },
         { id: 2, title: "Saga #2", where: "Saga Deluxe Vol. 1" },
       ],
     },
   ];

   ---------------------------------------------------------------
   Vai acrescentando séries a este array à medida que fores
   encontrando/partilhando novas na Telegram.
   ============================================================ */

const SERIES = [
  {
    id: "avengers-armageddon-reading-order",
    title: "Avengers: Armageddon",
    color: "#A6192E",
    chapters: [
      { id: 1, title: "Ultimate Spider-Man: Incursion #1", where: "", optional: true },
      { id: 2, title: "Ultimate Spider-Man: Incursion #2", where: "", optional: true },
      { id: 3, title: "Ultimate Spider-Man: Incursion #3", where: "", optional: true },
      { id: 4, title: "Ultimate Spider-Man: Incursion #4", where: "", optional: true },
      { id: 5, title: "Ultimate Spider-Man: Incursion #5", where: "", optional: true },
      { id: 6, title: "Captain America (2025) #1", where: "", optional: true },
      { id: 7, title: "Captain America (2025) #2", where: "", optional: true },
      { id: 8, title: "Captain America (2025) #3", where: "", optional: true },
      { id: 9, title: "Captain America (2025) #4", where: "", optional: true },
      { id: 10, title: "Captain America (2025) #5", where: "", optional: true },
      { id: 11, title: "Captain America (2025) #6", where: "", optional: false },
      { id: 12, title: "Captain America (2025) #7", where: "", optional: false },
      { id: 13, title: "Captain America (2025) #8", where: "", optional: false },
      { id: 14, title: "Captain America (2025) #9", where: "", optional: false },
      { id: 15, title: "Captain America (2025) #10", where: "", optional: false },
      { id: 16, title: "Will of Doom #1", where: "", optional: false },
      { id: 17, title: "Captain America (2025) #11", where: "", optional: false },
      { id: 18, title: "Armageddon/X-Men #1", where: "", optional: true },
      { id: 19, title: "Wolverine: Weapons of Armageddon #1", where: "", optional: false },
      { id: 20, title: "Wolverine: Weapons of Armageddon #2", where: "", optional: false },
      { id: 21, title: "Wolverine: Weapons of Armageddon #3", where: "", optional: false },
      { id: 22, title: "Wolverine: Weapons of Armageddon #4", where: "", optional: false },
      { id: 23, title: "Avengers: Armageddon #1", where: "Avengers: Armageddon (TP)", optional: false },
      { id: 24, title: "Avengers: Armageddon #2", where: "Avengers: Armageddon (TP)", optional: false },
      { id: 25, title: "Avengers: Armageddon #3", where: "Avengers: Armageddon (TP)", optional: false },
      { id: 26, title: "Avengers: Armageddon #4", where: "Avengers: Armageddon (TP)", optional: false },
      { id: 27, title: "Avengers: Armageddon #5", where: "Avengers: Armageddon (TP)", optional: false },
    ],
  },
  {
    id: "time-runs-out-secret-wars",
    title: "Time Runs Out & Secret Wars",
    color: "#8C1023",
    chapters: [
      { id: 1, title: "Secret Wars (1984) #1", where: "Secret Wars (1984)" },
      { id: 2, title: "Secret Wars (1984) #2", where: "Secret Wars (1984)" },
      { id: 3, title: "Secret Wars (1984) #3", where: "Secret Wars (1984)" },
      { id: 4, title: "Secret Wars (1984) #4", where: "Secret Wars (1984)" },
      { id: 5, title: "Secret Wars (1984) #5", where: "Secret Wars (1984)" },
      { id: 6, title: "Secret Wars (1984) #6", where: "Secret Wars (1984)" },
      { id: 7, title: "Secret Wars (1984) #7", where: "Secret Wars (1984)" },
      { id: 8, title: "Secret Wars (1984) #8", where: "Secret Wars (1984)" },
      { id: 9, title: "Secret Wars (1984) #9", where: "Secret Wars (1984)" },
      { id: 10, title: "Secret Wars (1984) #10", where: "Secret Wars (1984)" },
      { id: 11, title: "Secret Wars (1984) #11", where: "Secret Wars (1984)" },
      { id: 12, title: "Secret Wars (1984) #12", where: "Secret Wars (1984)" },
      { id: 13, title: "Books of Doom #1", where: "Books of Doom" },
      { id: 14, title: "Books of Doom #2", where: "Books of Doom" },
      { id: 15, title: "Books of Doom #3", where: "Books of Doom" },
      { id: 16, title: "Books of Doom #4", where: "Books of Doom" },
      { id: 17, title: "Books of Doom #5", where: "Books of Doom" },
      { id: 18, title: "Books of Doom #6", where: "Books of Doom" },
      { id: 19, title: "Dark Reign: Fantastic Four 1", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 20, title: "Dark Reign: Fantastic Four 2", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 21, title: "Dark Reign: Fantastic Four 3", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 22, title: "Dark Reign: Fantastic Four 4", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 23, title: "Dark Reign: Fantastic Four 5", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 24, title: "Fantastic Four 570", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 25, title: "Fantastic Four 571", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 26, title: "Fantastic Four 572", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 27, title: "Fantastic Four 573", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 28, title: "Fantastic Four 574", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 29, title: "Fantastic Four 575", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 30, title: "Fantastic Four 576", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 31, title: "Fantastic Four 577", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 32, title: "Fantastic Four 578", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 33, title: "Fantastic Four 579", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 34, title: "Fantastic Four 580", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 35, title: "Fantastic Four 581", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 36, title: "Fantastic Four 582", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 37, title: "Fantastic Four 583", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 38, title: "Fantastic Four 584", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 39, title: "Fantastic Four 585", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 40, title: "Fantastic Four 586", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 41, title: "Fantastic Four 587", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 42, title: "Fantastic Four 588", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 43, title: "FF 1", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 44, title: "FF 2", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 45, title: "FF 3", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 46, title: "FF 4", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 47, title: "FF 5", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 1" },
      { id: 48, title: "FF 6", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 49, title: "FF 7", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 50, title: "FF 8", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 51, title: "FF 9", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 52, title: "FF 10", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 53, title: "FF 11", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 54, title: "Fantastic Four 600", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 55, title: "FF 12", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 56, title: "Fantastic Four 601", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 57, title: "FF 13", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 58, title: "Fantastic Four 602", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 59, title: "FF 14", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 60, title: "Fantastic Four 603", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 61, title: "FF 15", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 62, title: "Fantastic Four 604", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 63, title: "FF 16", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 64, title: "Fantastic Four 605", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 65, title: "Fantastic Four 605.1", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 66, title: "Fantastic Four 606", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 67, title: "FF 17", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 68, title: "FF 18", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 69, title: "Fantastic Four 607", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 70, title: "Fantastic Four 608", where: "Fantastic Four by Jonathan Hickman Omnibus Vol. 2" },
      { id: 71, title: "FF 19", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 72, title: "FF 20", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 73, title: "FF 21", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 74, title: "Fantastic Four 609", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 75, title: "Fantastic Four 610", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 76, title: "FF 22", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 77, title: "Fantastic Four 611", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 78, title: "FF 23", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 79, title: "New Avengers 1", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 80, title: "New Avengers 2", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 81, title: "New Avengers 3", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 82, title: "Avengers 1", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 83, title: "Avengers 2", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 84, title: "Avengers 3", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 85, title: "Avengers 4", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 86, title: "Avengers 5", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 87, title: "Avengers 6", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 88, title: "New Avengers 4", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 89, title: "New Avengers 5", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 90, title: "New Avengers 6", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 91, title: "Avengers 7", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 92, title: "Avengers 8", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 93, title: "Avengers 9", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 94, title: "Avengers 10", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 95, title: "Avengers 11", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 96, title: "Avengers 12", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 97, title: "Avengers 13", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 98, title: "New Avengers 7", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 99, title: "Avengers 14", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 100, title: "Avengers 15", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 101, title: "Avengers 16", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 102, title: "Avengers 17", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 103, title: "Infinity 1", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 104, title: "New Avengers 8", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 105, title: "Avengers 18", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 106, title: "New Avengers 9", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 107, title: "Infinity 2", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 108, title: "New Avengers 10", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 109, title: "Avengers 19", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 110, title: "Infinity 3", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 111, title: "Avengers 20", where: "Avengers by Jonathan Hickman Omnibus Vol. 1" },
      { id: 112, title: "Infinity 4", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 113, title: "Avengers 21", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 114, title: "New Avengers 11", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 115, title: "Infinity 5", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 116, title: "Avengers 22", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 117, title: "Avengers 23", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 118, title: "Infinity 6", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 119, title: "New Avengers 12", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 120, title: "Avengers 24", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 121, title: "New Avengers 13", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 122, title: "New Avengers 14", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 123, title: "New Avengers 15", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 124, title: "Avengers 25", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 125, title: "Avengers 26", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 126, title: "Avengers 27", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 127, title: "Avengers 28", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 128, title: "Avengers 29", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 129, title: "Avengers 30", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 130, title: "Avengers 31", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 131, title: "Avengers 32", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 132, title: "Avengers 33", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 133, title: "Avengers 34", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 134, title: "New Avengers 16", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 135, title: "New Avengers 17", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 136, title: "New Avengers 18", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 137, title: "New Avengers 19", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 138, title: "New Avengers 20", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 139, title: "New Avengers 21", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 140, title: "New Avengers 22", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 141, title: "New Avengers 23", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 142, title: "Avengers 34.1", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 143, title: "Avengers 34.2", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 144, title: "Avengers 35", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 145, title: "New Avengers 24", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 146, title: "Avengers 36", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 147, title: "New Avengers 25", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 148, title: "Avengers 37", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 149, title: "New Avengers 26", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 150, title: "Avengers 38", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 151, title: "New Avengers 27", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 152, title: "Avengers 39", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 153, title: "New Avengers 28", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 154, title: "Avengers 40", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 155, title: "New Avengers 29", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 156, title: "Avengers 41", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 157, title: "New Avengers 30", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 158, title: "Avengers 42", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 159, title: "New Avengers 31", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 160, title: "New Avengers 32", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 161, title: "Avengers 43", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 162, title: "New Avengers 33", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 163, title: "Avengers 44", where: "Avengers by Jonathan Hickman Omnibus Vol. 2" },
      { id: 164, title: "Free Comic Book Day 2015: Secret Wars 0", where: "Secret Wars (2015)" },
      { id: 165, title: "Secret Wars 1", where: "Secret Wars (2015)" },
      { id: 166, title: "Secret Wars 2", where: "Secret Wars (2015)" },
      { id: 167, title: "Secret Wars 3", where: "Secret Wars (2015)" },
      { id: 168, title: "Secret Wars 4", where: "Secret Wars (2015)" },
      { id: 169, title: "Secret Wars 5", where: "Secret Wars (2015)" },
      { id: 170, title: "Secret Wars 6", where: "Secret Wars (2015)" },
      { id: 171, title: "Secret Wars 7", where: "Secret Wars (2015)" },
      { id: 172, title: "Secret Wars 8", where: "Secret Wars (2015)" },
      { id: 173, title: "Secret Wars 9", where: "Secret Wars (2015)" },
      { id: 174, title: "House of X #1", where: "House of X / Powers of X", optional: true },
      { id: 175, title: "Powers of X #1", where: "House of X / Powers of X", optional: true },
      { id: 176, title: "House of X #2", where: "House of X / Powers of X", optional: true },
      { id: 177, title: "Powers of X #2", where: "House of X / Powers of X", optional: true },
      { id: 178, title: "Powers of X #3", where: "House of X / Powers of X", optional: true },
      { id: 179, title: "House of X #3", where: "House of X / Powers of X", optional: true },
      { id: 180, title: "House of X #4", where: "House of X / Powers of X", optional: true },
      { id: 181, title: "Powers of X #4", where: "House of X / Powers of X", optional: true },
      { id: 182, title: "House of X #5", where: "House of X / Powers of X", optional: true },
      { id: 183, title: "Powers of X #5", where: "House of X / Powers of X", optional: true },
      { id: 184, title: "House of X #6", where: "House of X / Powers of X", optional: true },
      { id: 185, title: "Powers of X #6", where: "House of X / Powers of X", optional: true },
      { id: 186, title: "X-Men (2019) #1", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
      { id: 187, title: "X-Men (2019) #2", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
      { id: 188, title: "X-Men (2019) #3", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
      { id: 189, title: "X-Men (2019) #4", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
      { id: 190, title: "X-Men (2019) #5", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
      { id: 191, title: "X-Men (2019) #6", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
      { id: 192, title: "X-Men (2019) #7", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
      { id: 193, title: "X-Men (2019) #8", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
      { id: 194, title: "X-Men (2019) #9", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
      { id: 195, title: "Giant-Size X-Men: Jean Grey and Emma Frost #1", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
      { id: 196, title: "Giant-Size X-Men: Nightcrawler #1", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
      { id: 197, title: "X-Men (2019) #10", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
      { id: 198, title: "X-Men (2019) #11", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
      { id: 199, title: "Giant-Size X-Men: Magneto #1", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
      { id: 200, title: "Giant-Size X-Men: Fantomex #1", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
      { id: 201, title: "Giant-Size X-Men: Storm #1", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
      { id: 202, title: "Incoming! #1 (material do X-Men)", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
      { id: 203, title: "X-Men (2019) #16", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
      { id: 204, title: "X-Men (2019) #17", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
      { id: 205, title: "X-Men (2019) #18", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
      { id: 206, title: "X-Men (2019) #19", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
      { id: 207, title: "X-Men (2019) #20", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
      { id: 208, title: "X-Men (2019) #21", where: "X-Men by Jonathan Hickman Omnibus", optional: true },
    ],
  },
];
